[package]
url          = "https://github.com/sparsetech/pine/"
name         = "pine"
organisation = "tech.sparse"
developers   = [["tindzk", "Tim Nieradzik", "tim@sparse.tech"]]

[project]
scalaVersion   = "2.13.0"
scalaJsVersion = "0.6.28"
scalaOptions   = [
    "-deprecation",                      # Emit warning and location for usages of deprecated APIs.
    "-encoding", "utf-8",                # Specify character encoding used by source files.
    "-explaintypes",                     # Explain type errors in more detail.
    "-feature",                          # Emit warning and location for usages of features that should be imported explicitly.
    "-language:existentials",            # Existential types (besides wildcard types) can be written and inferred
    "-language:experimental.macros",     # Allow macro definition (besides implementation and application)
    "-language:higherKinds",             # Allow higher-kinded types
    "-unchecked",                        # Enable additional warnings where generated code depends on assumptions.
    "-Xcheckinit",                       # Wrap field accessors to throw an exception on uninitialized access.
    "-Xfatal-warnings",                  # Fail the compilation if there are any warnings.
    "-Xlint:adapted-args",               # Warn if an argument list is modified to match the receiver.
    "-Xlint:delayedinit-select",         # Selecting member of DelayedInit.
    "-Xlint:doc-detached",               # A Scaladoc comment appears to be detached from its element.
    "-Xlint:inaccessible",               # Warn about inaccessible types in method signatures.
    "-Xlint:infer-any",                  # Warn when a type argument is inferred to be `Any`.
    "-Xlint:missing-interpolator",       # A string literal appears to be missing an interpolator id.
    "-Xlint:nullary-override",           # Warn when non-nullary `def f()' overrides nullary `def f'.
    "-Xlint:nullary-unit",               # Warn when nullary methods return Unit.
    "-Xlint:option-implicit",            # Option.apply used implicit view.
    "-Xlint:package-object-classes",     # Class or object defined in package object.
    "-Xlint:poly-implicit-overload",     # Parameterized overloaded implicit methods are not visible as view bounds.
    "-Xlint:private-shadow",             # A private field (or class parameter) shadows a superclass field.
    "-Xlint:stars-align",                # Pattern sequence wildcard must align with sequence component.
    "-Xlint:type-parameter-shadow",      # A local type parameter shadows a type already in scope.
#    "-Ywarn-dead-code",                  # Warn when dead code is identified.
    "-Ywarn-numeric-widen",              # Warn when numerics are widened.

    ### post-11 options ###

    "-Xlint:constant",                   # Evaluation of a constant arithmetic expression results in an error.
    "-Ywarn-extra-implicit",             # Warn when more than one implicit parameter section is defined.
    "-Ywarn-unused:imports",             # Warn if an import selector is not referenced.
    "-Ywarn-unused:locals",              # Warn if a local definition is unused.
    "-Ywarn-unused:patvars",             # Warn if a variable bound in a pattern is unused.
    "-Ywarn-unused:privates",            # Warn if a private member is unused.
    #    "-Ywarn-unused:implicits",           # Warn if an implicit parameter is unused.
    #    "-Ywarn-unused:params",              # Warn if a value parameter is unused.
    #    "-Ywarn-value-discard"               # Warn when non-Unit expression results are unused.
]
testFrameworks = [
  "org.scalatest.tools.Framework",
  "org.scalacheck.ScalaCheckFramework"
]

[module.pine]
root    = "src/main/scala"
sources = ["src/main/scala"]
targets = ["js", "jvm"]

[module.pine.test]
sources   = ["src/test/scala"]
targets   = ["js", "jvm"]
scalaDeps = [
  ["org.scalatest" , "scalatest" , "3.0.8" ],
  ["org.scalacheck", "scalacheck", "1.14.0"]
]

[module.pine.jvm]
root    = "src/main/scala-jvm"
sources = ["src/main/scala-jvm"]

[module.pine.js]
root    = "src/main/scala-js"
sources = ["src/main/scala-js"]
scalaDeps = [
  ["org.scala-js", "scalajs-dom", "0.9.7"]
]

[module.pine.test.js]
jsdom   = true
sources = ["src/test/scala-js"]
